Add files via upload
NovaTecConsulting/JMeter-InfluxDB-Writer pull request #12
Opened 2017-05-22 20:31 UTC by MooreDerek

Issue 11 - Added ability to record sub samples. This controlled by the parameter 'recordSubSamples'. Also, made it optional to provide a Database User, the current code forces the 'jmeter' user, which can be a pain when running basic tests.

2017-05-23 11:56 UTC, AlexanderWert requested changes

2017-05-23 11:56 UTC, AlexanderWert commented on src/main/java/rocks/nt/apm/jmeter/JMeterInfluxDBBackendListenerClient.java
> +		String recordSubSamples = context.getParameter(KEY_RECORD_SUB_SAMPLES, "");
Please create a **boolean** variable "recordSubSamples" that is initialized in the setupTest(....) method.

2017-05-23 11:56 UTC, AlexanderWert commented on src/main/java/rocks/nt/apm/jmeter/JMeterInfluxDBBackendListenerClient.java
> +            if(null != recordSubSamples && recordSubSamples.equals("true")) {
Please use the above mentioned boolean variable for this if condition.

2017-05-23 11:56 UTC, AlexanderWert commented on src/main/java/rocks/nt/apm/jmeter/JMeterInfluxDBBackendListenerClient.java
> +			LOGGER.error("Failed  to influx", e);
Why is "writing" removed?

2017-05-23 11:56 UTC, AlexanderWert commented on src/main/java/rocks/nt/apm/jmeter/JMeterInfluxDBBackendListenerClient.java
> +			if ((null != regexForSamplerList && sampleResult.getSampleLabel().matches(regexForSamplerList)) ||
If possible, please avoid the changes in line breaks.

2017-05-23 20:53 UTC, MooreDerek commented
@AlexanderWert - thanks for taking the time to review.  I've addressed all comments in review and committed the changes.

2017-05-24 05:16 UTC, AlexanderWert approved these changes

2017-05-24 05:17 UTC, AlexanderWert approved these changes

2017-05-24 05:17 UTC, merged